os: osx
language: objective-c

matrix:
  include:
    - osx_image: xcode10.1
      env: 
        - SDK_VERSION=10.12
    - osx_image: xcode9.4
    - osx_image: xcode6.4
    
script:
  - set -o pipefail
  - find . -type f -exec sed -i -e 's|scroll|scroll_|g' {} \;
  - xcodebuild -project ./macOS/btx_decoder.xcodeproj -sdk macosx -arch x86_64
