os: osx
language: objective-c

matrix:
  include:
    - osx_image: xcode10.1
      env: 
        - SDK_VERSION=10.7 SDKROOT=MacOSX10.7.sdk

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Downloading ${MACOSX_DEPLOYMENT_TARGET} sdk"
      curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX${SDK_VERSION}.sdk.tar.xz
      sudo tar xf MacOSX*.sdk.tar.xz -C /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
      ls -lh /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
      plutil -replace MinimumSDKVersion -string ${SDK_VERSION} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
      plutil -replace DTSDKName -string macosx${SDK_VERSION}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
      sed -i -e 's|MACOSX_DEPLOYMENT_TARGET = 10.13|MACOSX_DEPLOYMENT_TARGET = 10.7|g' ./macOS/btx_decoder.xcodeproj/project.pbxproj
      xcodebuild -version -sdk
      set -o pipefail
      xcodebuild -project ./macOS/btx_decoder.xcodeproj -sdk MacOSX10.7.sdk -arch x86_64
      mkdir -p out ; hdiutil create -format UDZO -srcfolder macOS/build/Release/ out/btx_decoder-$(git rev-parse --short HEAD).dmg
    fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
