os: osx
language: objective-c

matrix:
  include:
    - osx_image: xcode10.1
      env: 
        - SDK_VERSION=10.7 MACOSX_DEPLOYMENT_TARGET=10.7 SDKROOT=macosx10.7

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Downloading ${MACOSX_DEPLOYMENT_TARGET} sdk"
      curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz
      tar -xf MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz -C "$(dirname "$CONDA_BUILD_SYSROOT")"  
      plutil -replace MinimumSDKVersion -string ${MACOSX_DEPLOYMENT_TARGET} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
      plutil -replace DTSDKName -string macosx${MACOSX_DEPLOYMENT_TARGET}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
      set -o pipefail
      xcodebuild -project ./macOS/btx_decoder.xcodeproj -sdk macosx -arch x86_64
      mkdir -p out ; hdiutil create -format UDZO -srcfolder macOS/build/Release/ out/btx_decoder-$(git rev-parse --short HEAD).dmg
    fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
