matrix:
  include:
    - os: linux
      language: c
      dist: trusty
      sudo: required
    - os: osx
      language: objc
      osx_image: xcode10.1
      env: 
        - SDK_VERSION=10.9 SDKROOT=macosx10.9

addons:
  apt:
    packages:
      - libsdl2-dev

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Downloading ${MACOSX_DEPLOYMENT_TARGET} sdk"
      curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX${SDK_VERSION}.sdk.tar.xz
      sudo tar xf MacOSX*.sdk.tar.xz -C /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
      ls -lh /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
      plutil -replace MinimumSDKVersion -string ${SDK_VERSION} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
      plutil -replace DTSDKName -string macosx${SDK_VERSION}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
      sed -i -e 's|MACOSX_DEPLOYMENT_TARGET = 10.13|MACOSX_DEPLOYMENT_TARGET = 10.9|g' ./macOS/btx_decoder.xcodeproj/project.pbxproj
      xcodebuild -version -sdk
      set -o pipefail
      xcodebuild -project ./macOS/btx_decoder.xcodeproj -sdk $SDKROOT -arch x86_64
      mkdir -p out ; hdiutil create -format UDZO -srcfolder macOS/build/Release/ out/btx_decoder-$(git rev-parse --short HEAD).dmg
    elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd sdl/
      make
      strip btx-sdl
      mkdir -p appdir/usr/bin ; cp btx-sdl appdir/usr/bin/
      mkdir -p appdir/usr/share/icons/hicolor/256x256/apps ; cp bildschirmtext.png appdir/usr/share/icons/hicolor/256x256/apps/
      mkdir -p appdir/usr/share/applications ; cp btx-sdl.desktop appdir/usr/share/applications/
      wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      chmod a+x linuxdeployqt-continuous-x86_64.AppImage
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
      mkdir -p ../out ; cp btx-sdl BTX*.AppImage* ../out/
      cd ..
    fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
