os: osx
language: objective-c

matrix:
  include:
    - osx_image: xcode10.1
      env: 
        - SDK_VERSION=10.9

script:
  - set -o pipefail
  - xcodebuild -project ./macOS/btx_decoder.xcodeproj -sdk macosx -arch x86_64
